#!/bin/bash
# /etc/init.d/open_door_init

### BEGIN INIT INFO
# Provides:          open_door
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to manage a servo
### END INIT INFO


case "$1" in 
    start)
        echo "Starting open_ddor"
        python /home/pi/TrapHouse/open_door.py &
        ;;
    stop)
        echo "Stopping open_door"
        ps aux | grep [o]pen_door.py | awk '{print $2}' | xargs kill
        ;;
    *)
        echo "Usage: /etc/init.d/open_door_init start|stop"
        exit 1
        ;;
esac

exit 0
